### PR TITLE
build tests sysroot with DI

### PR DESCRIPTION
**Pull request by qjerome**
Build tests sysroot with DI:

- fixed ignore-inline-never.rs that is failing because of FileCheck matching DI instead of expected check
- removed `lto=true` from BTF tests

NB: this requires patched LLVM https://github.com/rust-lang/llvm-project/commit/d06f0cd0977dd16f09c259133f36c7e8b9f0d322

### CODE REVIEW

**Comment by tamird** [comment]
Looks like we need to add this branch to the ci config: https://github.com/aya-rs/bpf-linker/blob/a637e6b1c61ab35ade940b6b9b3310f0b4294128/.github/workflows/ci.yml#L7

**Comment by qjerome** [comment]
Am I supposed to do anything ?

**Comment by tamird** [comment]
Oops, misclick.

Yes, please add "fix-di" to the CI config for both branch builds and pull request builds.

**Comment by qjerome** [comment]
I have no push rights on bpf-linker so this would have to go to another round of PR ! Wouldn't it be easier if any of the maintainers would make that change to the GH actions ?

**Comment by tamird** [comment]
ah, right, because it has to go on the master branch. Sure, I'll send a PR.

**Comment by qjerome** [comment]
thanks

**Comment by vadorovsky** [comment]
@qjerome can you rebase to trigger the CI?

**Comment by tamird** [comment]
CI is blocked on https://github.com/aya-rs/aya/pull/725

**Comment by qjerome** [comment]
Yeah, that's what I just saw (that it is still blocked) ... Will wait after that before rebasing then

**Comment by tamird** [comment]
@qjerome please rebase.

**Comment by qjerome** [comment]
All your changes have not been synced with fix-di branch is that normal ?

**Comment by tamird** [comment]
Yes, let's see what happens.

**Comment by qjerome** [comment]
Done in https://github.com/aya-rs/bpf-linker/pull/95

**Comment by tamird** [comment]
Why not do it in this PR?

It does seem like we need to rebase feature/fix-di to pick up the CI changes, I'll do that later on this morning.

**Comment by tamird** [comment]
OK, please rebase now.

**Pull request closed without merging**
