### PR TITLE
Appease nightly clippy

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Review by vadorovsky — APPROVED** [review]

**Comment by vadorovsky** [comment]
This failure seems legit though, it seems like linking with C module (providing an anon struct) regressed:

```
stderr:
  ------------------------------------------
  error: linking with `/home/runner/work/bpf-linker/bpf-linker/target/debug/bpf-linker` failed: exit status: 2
    |
    = note: LC_ALL="C" PATH="/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/x86_64-unknown-linux-gnu/bin:/usr/lib/llvm-18/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "/home/runner/work/bpf-linker/bpf-linker/target/debug/bpf-linker" "--export-symbols" "/tmp/rustck3t50V/symbols" "/tmp/rustck3t50V/symbols.o" "/tmp/assembly/anon_struct_c.anon_struct_c.e9732f78866b9042-cgu.0.rcgu.o" "-L" "/tmp" "-L" "/home/runner/work/bpf-linker/bpf-linker/target/debug/deps" "-L" "/home/runner/work/bpf-linker/bpf-linker/target/debug" "-L" "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib" "-L" "target/bitcode" "-L" "/tmp/assembly/anon_struct_c.stage-id.aux" "-L" "/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/bpfel-unknown-none/lib" "target/bitcode/anon.bc" "/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/bpfel-unknown-none/lib/librustc_std_workspace_core-2[145](https://github.com/aya-rs/bpf-linker/actions/runs/8734403365/job/23965020239?pr=196#step:16:146)dea74949bc48.rlib" "/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/bpfel-unknown-none/lib/libcore-530cb4bfa41b092b.rlib" "/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/bpfel-unknown-none/lib/libcompiler_builtins-60fc49e7bc4ee087.rlib" "--cpu" "generic" "-L" "/home/runner/work/bpf-linker/bpf-linker/target/sysroot/lib/rustlib/bpfel-unknown-none/lib" "-o" "/tmp/assembly/anon_struct_c.s" "-O0" "--debug" "--emit=obj" "--btf" "--emit=asm"
    = note: error: failure linking module target/bitcode/anon.bc
```

I can try to fix it later today if you need.

**Comment by tamird** [comment]
Yeah it seems the regression is somewhere in https://github.com/rust-lang/rust/compare/1cec373f6...becebb315. I don't have a Linux machine on hand so I'd appreciate your help. I'm trying to get better output in CI.

**Comment by tamird** [comment]
Well I got more output, but it's not super helpful:
```
    = note: ERROR llvm: Invalid record
            Error: failure linking module target/bitcode/anon.bc
```

**Comment by tamird** [comment]
@vadorovsky I've pinned nightly to 2024-04-16 to unblock this. I extracted the logging changes to https://github.com/aya-rs/bpf-linker/pull/197 which I'll rebase after this merges.

**Comment by vadorovsky** [comment]
Awesome! Sorry that I didn't help yesterday. Hopefully I will find some time to bisect today.

**Comment by tamird** [comment]
@vadorovsky been a few months and we're still pinned. Would be really good to figure this out.

**Pull request merged**
